//Actions types--------------------------------------------------------------------
export const
    EXHIBIT_CHANGE_PAGE = "EXHIBIT_CHANGE_PAGE",
    CHANGE_EXHIBIT_LANGUAGE = "CHANGE_EXHIBIT_LANGUAGE",

    //EXHIBIT CREATE PAGE

    SUBMIT_NEW_EXHIBIT = "SUBMIT_NEW_EXHIBIT",
    SUBMIT_NEW_EXHIBIT_REQUEST = "SUBMIT_NEW_EXHIBIT_REQUEST",
    SUBMIT_NEW_EXHIBIT_RESPONSE = "SUBMIT_NEW_EXHIBIT_RESPONSE",
    CLEAR_CREATE_EXHIBIT = "CLEAR_CREATE_EXHIBIT",

    //ERROR INFORMER
    HIDE_ERROR_WINDOW = "HIDE_ERROR_WINDOW",
    SHOW_ERROR_WINDOW = "SHOW_ERROR_WINDOW",
    
    EXHIBIT_OVERVIEW_FETCH_LIST = "EXHIBIT_OVERVIEW_FETCH_LIST",
    EXHIBIT_OVERVIEW_FETCH_LIST_REQUEST = "EXHIBIT_OVERVIEW_FETCH_LIST_REQUEST",
    EXHIBIT_OVERVIEW_FETCH_LIST_RESPOSE = "EXHIBIT_OVERVIEW_FETCH_LIST_RESPOSE",

    DELETE_EXHIBIT = "DELETE_EXHIBIT",
    DELETE_EXHIBIT_RESPONSE = "DELETE_EXHIBIT_RESPONSE",
    DELETE_EXHIBIT_FROM_LIST = "DELETE_EXHIBIT_FROM_LIST",

    EDIT_EXHIBIT = "EDIT_EXHIBIT",
    GET_EXHIBIT_RESPONSE = "GET_EXHIBIT_RESPONSE",

    SUBMIT_EXHIBIT_UPDATE = "SUBMIT_EXHIBIT_UPDATE",
    SUBMIT_EXHIBIT_UPDATE_REQUEST = "SUBMIT_EXHIBIT_UPDATE_REQUEST",
    SUBMIT_EXHIBIT_UPDATE_RESPONSE = "SUBMIT_EXHIBIT_UPDATE_RESPONSE",
    
    //NAVBAR
    NAVBAR_OPEN = "NAVBAR_OPEN",
    NAVBAR_CLOSE = "NAVBAR_CLOSE",
    
    //INST
    FETCH_INST = "FETCH_INST",
    FETCH_INST_REQUEST = "FETCH_INST_REQUEST",
    FETCH_INST_RESPONSE = "FETCH_INST_RESPONSE",
    

    NONE = "NONE"
    ;