//Actions types--------------------------------------------------------------------
export const
    CHANGE_PAGE = "CHANGE_PAGE",
    //EXHIBIT CREATOR
    CHANGE_EXHIBIT_LANGUAGE = "CHANGE_EXHIBIT_LANGUAGE",

    SUBMIT_NEW_EXHIBIT = "SUBMIT_NEW_EXHIBIT",
    SUBMIT_NEW_EXHIBIT_REQUEST = "SUBMIT_NEW_EXHIBIT_REQUEST",
    SUBMIT_NEW_EXHIBIT_RESPONSE = "SUBMIT_NEW_EXHIBIT_RESPONSE",
    HIDE_ERROR_WINDOW = "HIDE_ERROR_WINDOW",
    SHOW_ERROR_WINDOW = "SHOW_ERROR_WINDOW",
    
    OVERVIEW_FETCH_LIST = "OVERVIEW_FETCH_LIST",
    OVERVIEW_FETCH_LIST_REQUEST = "OVERVIEW_FETCH_LIST_REQUEST",
    OVERVIEW_FETCH_LIST_RESPOSE = "OVERVIEW_FETCH_LIST_RESPOSE",

    DELETE_EXHIBIT = "DELETE_EXHIBIT",
    DELETE_EXHIBIT_RESPONSE = "DELETE_EXHIBIT_RESPONSE",
    DELETE_EXHIBIT_FROM_LIST = "DELETE_EXHIBIT_FROM_LIST"
    ;