//Actions types--------------------------------------------------------------------
export const
    BUREAU_CHANGE_PAGE = "BUREAU_CHANGE_PAGE",
    CHANGE_BUREAU_LANGUAGE = "CHANGE_BUREAU_LANGUAGE",

    //BUREAU CREATE PAGE

    SUBMIT_NEW_BUREAU = "SUBMIT_NEW_BUREAU",
    SUBMIT_NEW_BUREAU_REQUEST = "SUBMIT_NEW_BUREAU_REQUEST",
    SUBMIT_NEW_BUREAU_RESPONSE = "SUBMIT_NEW_BUREAU_RESPONSE",
    CLEAR_CREATE_BUREAU = "CLEAR_CREATE_BUREAU",

    //ERROR INFORMER
    HIDE_ERROR_WINDOW = "HIDE_ERROR_WINDOW",
    SHOW_ERROR_WINDOW = "SHOW_ERROR_WINDOW",
    
    //BUREAU OVERVIEW PAGE
    BUREAU_OVERVIEW_FETCH_LIST = "BUREAU_OVERVIEW_FETCH_LIST",
    BUREAU_OVERVIEW_FETCH_LIST_REQUEST = "BUREAU_OVERVIEW_FETCH_LIST_REQUEST",
    BUREAU_OVERVIEW_FETCH_LIST_RESPOSE = "BUREAU_OVERVIEW_FETCH_LIST_RESPOSE",

    DELETE_BUREAU = "DELETE_BUREAU",
    DELETE_BUREAU_RESPONSE = "DELETE_BUREAU_RESPONSE",
    DELETE_BUREAU_FROM_LIST = "DELETE_BUREAU_FROM_LIST",

    //BUREAU EDIT PAGE
    EDIT_BUREAU = "EDIT_BUREAU",
    GET_BUREAU_RESPONSE = "GET_BUREAU_RESPONSE",

    BUREAU_CHANGE_COMPLEX_REQUEST = "BUREAU_CHANGE_COMPLEX_REQUEST",
    BUREAU_CHANGE_COMPLEX_RESPONSE = "BUREAU_CHANGE_COMPLEX_RESPONSE",
    BUREAU_APPLY_CHANGE_COMPLEX = "BUREAU_APPLY_CHANGE_COMPLEX",

    SUBMIT_BUREAU_UPDATE = "SUBMIT_BUREAU_UPDATE",
    SUBMIT_BUREAU_UPDATE_REQUEST = "SUBMIT_BUREAU_UPDATE_REQUEST",
    SUBMIT_BUREAU_UPDATE_RESPONSE = "SUBMIT_BUREAU_UPDATE_RESPONSE",

    BUREAU_RESET_EDIT_DATA = "BUREAU_RESET_EDIT_DATA",
    
    //NAVBAR
    NAVBAR_OPEN = "NAVBAR_OPEN",
    NAVBAR_CLOSE = "NAVBAR_CLOSE",
    
    //INST
    FETCH_INST = "FETCH_INST",
    FETCH_INST_REQUEST = "FETCH_INST_REQUEST",
    FETCH_INST_RESPONSE = "FETCH_INST_RESPONSE",
    INST_CHANGE = "INST_CHANGE",
    INST_SUBMIT_UPDATE_RESPONSE = "INST_SUBMIT_UPDATE_RESPONSE",
    INST_SUBMIT_DELETE_RESPONSE = "INST_SUBMIT_DELETE_RESPONSE",
    
    //SUCCESS INFORMER
    SHOW_SUCCESS_INFORMER = "SHOW_SUCCESS_INFORMER",
    HIDE_SUCCESS_INFORMER = "HIDE_SUCCESS_INFORMER",

    NONE = "NONE"
    ;