//Actions types--------------------------------------------------------------------
export const
    DESIGNER_CHANGE_PAGE = "DESIGNER_CHANGE_PAGE",
    CHANGE_DESIGNER_LANGUAGE = "CHANGE_DESIGNER_LANGUAGE",

    //DESIGNER CREATE PAGE

    SUBMIT_NEW_DESIGNER = "SUBMIT_NEW_DESIGNER",
    SUBMIT_NEW_DESIGNER_REQUEST = "SUBMIT_NEW_DESIGNER_REQUEST",
    SUBMIT_NEW_DESIGNER_RESPONSE = "SUBMIT_NEW_DESIGNER_RESPONSE",
    CLEAR_CREATE_DESIGNER = "CLEAR_CREATE_DESIGNER",

    //ERROR INFORMER
    HIDE_ERROR_WINDOW = "HIDE_ERROR_WINDOW",
    SHOW_ERROR_WINDOW = "SHOW_ERROR_WINDOW",
    
    DESIGNER_OVERVIEW_FETCH_LIST = "DESIGNER_OVERVIEW_FETCH_LIST",
    DESIGNER_OVERVIEW_FETCH_LIST_REQUEST = "DESIGNER_OVERVIEW_FETCH_LIST_REQUEST",
    DESIGNER_OVERVIEW_FETCH_LIST_RESPOSE = "DESIGNER_OVERVIEW_FETCH_LIST_RESPOSE",

    DELETE_DESIGNER = "DELETE_DESIGNER",
    DELETE_DESIGNER_RESPONSE = "DELETE_DESIGNER_RESPONSE",
    DELETE_DESIGNER_FROM_LIST = "DELETE_DESIGNER_FROM_LIST",

    EDIT_DESIGNER = "EDIT_DESIGNER",
    GET_DESIGNER_RESPONSE = "GET_DESIGNER_RESPONSE",

    SUBMIT_DESIGNER_UPDATE = "SUBMIT_DESIGNER_UPDATE",
    SUBMIT_DESIGNER_UPDATE_REQUEST = "SUBMIT_DESIGNER_UPDATE_REQUEST",
    SUBMIT_DESIGNER_UPDATE_RESPONSE = "SUBMIT_DESIGNER_UPDATE_RESPONSE",
    
    DESIGNER_RESET_EDIT_DATA = "DESIGNER_RESET_EDIT_DATA",

    //NAVBAR
    NAVBAR_OPEN = "NAVBAR_OPEN",
    NAVBAR_CLOSE = "NAVBAR_CLOSE",
    
    //CATSUB
    DESIGNER_CATSUB_CHANGE = "DESIGNER_CATSUB_CHANGE",
    DESIGNER_CHANGE_COUNTRIES = "DESIGNER_CHANGE_COUNTRIES",


    NONE = "NONE"
    ;