//Actions types--------------------------------------------------------------------
export const
    GOLO_CHANGE_PAGE = "GOLO_CHANGE_PAGE",
    CHANGE_GOLO_LANGUAGE = "CHANGE_GOLO_LANGUAGE",

    //GOLO CREATE PAGE

    SUBMIT_NEW_GOLO = "SUBMIT_NEW_GOLO",
    SUBMIT_NEW_GOLO_REQUEST = "SUBMIT_NEW_GOLO_REQUEST",
    SUBMIT_NEW_GOLO_RESPONSE = "SUBMIT_NEW_GOLO_RESPONSE",
    CLEAR_CREATE_GOLO = "CLEAR_CREATE_GOLO",

    //ERROR INFORMER
    HIDE_ERROR_WINDOW = "HIDE_ERROR_WINDOW",
    SHOW_ERROR_WINDOW = "SHOW_ERROR_WINDOW",
    
    GOLO_OVERVIEW_FETCH_LIST = "GOLO_OVERVIEW_FETCH_LIST",
    GOLO_OVERVIEW_FETCH_LIST_REQUEST = "GOLO_OVERVIEW_FETCH_LIST_REQUEST",
    GOLO_OVERVIEW_FETCH_LIST_RESPOSE = "GOLO_OVERVIEW_FETCH_LIST_RESPOSE",

    DELETE_GOLO = "DELETE_GOLO",
    DELETE_GOLO_RESPONSE = "DELETE_GOLO_RESPONSE",
    DELETE_GOLO_FROM_LIST = "DELETE_GOLO_FROM_LIST",

    EDIT_GOLO = "EDIT_GOLO",
    GET_GOLO_RESPONSE = "GET_GOLO_RESPONSE",

    SUBMIT_GOLO_UPDATE = "SUBMIT_GOLO_UPDATE",
    SUBMIT_GOLO_UPDATE_REQUEST = "SUBMIT_GOLO_UPDATE_REQUEST",
    SUBMIT_GOLO_UPDATE_RESPONSE = "SUBMIT_GOLO_UPDATE_RESPONSE",
    
    //NAVBAR
    NAVBAR_OPEN = "NAVBAR_OPEN",
    NAVBAR_CLOSE = "NAVBAR_CLOSE",

    NONE = "NONE"
    ;