//Actions types--------------------------------------------------------------------
export const
    TUPLE_CHANGE_PAGE = "TUPLE_CHANGE_PAGE",
    CHANGE_TUPLE_LANGUAGE = "CHANGE_TUPLE_LANGUAGE",

    //TUPLE CREATE PAGE

    SUBMIT_NEW_TUPLE = "SUBMIT_NEW_TUPLE",
    SUBMIT_NEW_TUPLE_REQUEST = "SUBMIT_NEW_TUPLE_REQUEST",
    SUBMIT_NEW_TUPLE_RESPONSE = "SUBMIT_NEW_TUPLE_RESPONSE",
    CLEAR_CREATE_TUPLE = "CLEAR_CREATE_TUPLE",

    //ERROR INFORMER
    HIDE_ERROR_WINDOW = "HIDE_ERROR_WINDOW",
    SHOW_ERROR_WINDOW = "SHOW_ERROR_WINDOW",
    
    TUPLE_OVERVIEW_FETCH_LIST = "TUPLE_OVERVIEW_FETCH_LIST",
    TUPLE_OVERVIEW_FETCH_LIST_REQUEST = "TUPLE_OVERVIEW_FETCH_LIST_REQUEST",
    TUPLE_OVERVIEW_FETCH_LIST_RESPOSE = "TUPLE_OVERVIEW_FETCH_LIST_RESPOSE",

    DELETE_TUPLE = "DELETE_TUPLE",
    DELETE_TUPLE_RESPONSE = "DELETE_TUPLE_RESPONSE",
    DELETE_TUPLE_FROM_LIST = "DELETE_TUPLE_FROM_LIST",

    EDIT_TUPLE = "EDIT_TUPLE",
    GET_TUPLE_RESPONSE = "GET_TUPLE_RESPONSE",

    SUBMIT_TUPLE_UPDATE = "SUBMIT_TUPLE_UPDATE",
    SUBMIT_TUPLE_UPDATE_REQUEST = "SUBMIT_TUPLE_UPDATE_REQUEST",
    SUBMIT_TUPLE_UPDATE_RESPONSE = "SUBMIT_TUPLE_UPDATE_RESPONSE",
    
    //NAVBAR
    NAVBAR_OPEN = "NAVBAR_OPEN",
    NAVBAR_CLOSE = "NAVBAR_CLOSE",
    
    //CATSUB
    TUPLE_CATSUB_CHANGE = "TUPLE_CATSUB_CHANGE",


    NONE = "NONE"
    ;